# Generated by Django 2.2.4 on 2019-08-08 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签页',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='美食店名', max_length=30, verbose_name='美食店名')),
                ('level', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], help_text='等级', verbose_name='等级')),
                ('desc', models.TextField(default='', help_text='等级描述', verbose_name='等级描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('zan', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], help_text='点赞数', verbose_name='点赞数')),
                ('tags', models.ManyToManyField(blank=True, to='foods.Tags', verbose_name='店铺标签')),
            ],
            options={
                'verbose_name': '美食店信息表',
                'verbose_name_plural': '美食店信息表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='佚名', max_length=20, verbose_name='姓名')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ShopInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.ShopInfo', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论',
                'ordering': ['-create_time'],
            },
        ),
    ]
